### PR TITLE
Add doc/tty-share-bash_completion

### PR DESCRIPTION
**Pull request by fvcr**
bash completion for tty-share

### CODE REVIEW

**Comment by elisescu** [comment]
Hey @fvcr ! Thanks for your PR. Do you know if there's an easy way to automatically generate this, or to check if it's still up to date?
I wonder if there is no go lib to wrap around the existing command line arguments and have an new command line argument that would dump a file like this.

**Comment by elisescu** [comment]
Merging it

**Comment by fvcr** [comment]
I generated it manually,

I had a look at the [vt-cli](https://github.com/VirusTotal/vt-cli/blob/master/cmd/completion.go) code and as I understand it they generate with [github.com/spf13/cobra](https://github.com/spf13/cobra).

Cheers!

**Comment by fvcr** [comment]
Hi @elisescu,

I found something written in Ruby, [completely](https://rubygems.org/gems/completely), maybe that could be useful.

"Generate bash completion scripts using simple YAML configuration"
https://github.com/DannyBen/completely

**Comment by elisescu** [comment]
Thanks, @fvcr :).

Completely unrelated and out of curiosity, are you still using tty-share, or not anymore. If yes, what's your typical usecase, and are you using with your own tty-proxy instance?

**Comment by fvcr** [comment]
Hi @elisescu,
Sorry for the long delay!

> 
> Completely unrelated but taking advantage of this thread: are you still using tty-share, or not anymore?

Yes, I still use it.


>
> If yes, what's your typical usecase, and are you using with your own tty-proxy instance? Just curious :).

My typical use case was to provide support to a person who needs to make a specific configuration on their machine.
I use your tty-proxy instance, I'd like to package tty-proxy for Debian, but I haven't been able to stop and analyze it more calmly yet.

Thanks again for your work!

**Comment by elisescu** [comment]
Thanks for getting back to me, @fvcr, and great to hear you're still using it. Are any features you felt like would have been nice to have? I won't promise I'll add them, but perhaps when/if I end up having some more time to put into it, I can take them into account. For example I found myself sometimes needing a file from the remote machine and was thinking would be nice to add some support for easy file transfer in either direction, but didn't look too much into it yet (also want to keep it simple and minimalistic).

Random fun fact: I was working on adding some integration testing on a project via Github actions, and instead of the long loop of pushing minor changes until I fixed the issues I was having only when the code was running inside the action, I downloaded tty-share inside the runner and got remote terminal access and could figure out why the code was not working directly on the runner. Not only that, but also also do portforwarding (`tty-share -L 2000:localhost:3000  https://on.tty-share.com/s/oxsf7Y2....`) so could access stuff running in the runner from my local browser.

Here's the GH action step in case you ever need something like that :)

```
- name: Get tty-share
  if: always()
  run: |
    curl -L https://github.com/elisescu/tty-share/releases/download/v2.4.0/tty-share_linux-amd64 -o tty-share
    chmod u+x ./tty-share
    export TERM=xterm-256color
    ./tty-share -A --public --headless --headless-cols 255 --headless-rows 50 --no-wait --listen :8001
```

**Pull request merged**
